[DRAFT] Issue using `ndarray-rand`
hicder/muopdb pull request #84
Opened 2024-11-09 03:57 UTC by tvhong

I want to use `ndarray-rand` to generate a random orthogonal matrix for RabitQ. However, I can't seem to get `Array::random` to work, even when I use the example code from https://docs.rs/ndarray-rand/latest/ndarray_rand/trait.RandomExt.html#tymethod.random .

Does anyone know what I did wrong here?

```
error[E0599]: no function or associated item named `random` found for struct `ArrayBase` in the current scope
   --> rs/quantization/src/rabitq_builder.rs:6:20
    |
6   |     let a = Array::random(2, Uniform::new(0., 10.));
    |                    ^^^^^^ function or associated item not found in `ArrayBase<OwnedRepr<_>, _>`
    |
note: if you're trying to build a new `ArrayBase<OwnedRepr<_>, _>` consider using one of the following associated functions:
      ndarray::impl_constructors::<impl ArrayBase<S, Dim<[usize; 1]>>>::from_vec
      ndarray::impl_constructors::<impl ArrayBase<S, Dim<[usize; 1]>>>::from_iter
      ndarray::impl_constructors::<impl ArrayBase<S, Dim<[usize; 1]>>>::linspace
      ndarray::impl_constructors::<impl ArrayBase<S, Dim<[usize; 1]>>>::range
      and 15 others
```

2024-11-10 22:10 UTC, tyb0807 reviewed
Thanks! Just one high level question, why `Array1` and `Array2` instead of `Vec` and `Vec<Vec>`? Asking just for the sake of consistency with other parts of the code base.

2024-11-10 22:47 UTC, tvhong commented
@tyb0807 The querying phase needs to do some matrix multiplication and vector dot products (see https://github.com/hicder/muopdb/issues/32#issuecomment-2466578455). So, I store these as ndarray objects.

That being said, I'm not set on the data type at the moment. Maybe `ndarray` doesn't support serialization well, or that we should use `nalgebra` since we're only dealing with low-dimensionality data. Once that happens, we can easily change the data type.

2024-11-14 17:10 UTC, hicder requested changes
you'll need to use the normalized vector

2024-12-01 06:34 UTC, tvhong commented on rs/quantization/src/rabitq.rs
> +}
I see. Running `cargo fmt` fixed this.

2024-12-01 06:35 UTC, tvhong commented
Updated the code to use normalized vectors instead.

2024-12-01 13:45 UTC, merged